services:
    foundry:
      image: felddy/foundryvtt:release
      hostname: my_foundry_host
      init: true
      restart: "unless-stopped"
      volumes:
        - type: bind
          source: /foundry-data
          target: /data
      environment:
        - CONTAINER_CACHE=/data/container_cache
        - CONTAINER_PATCH_URLS=https://raw.githubusercontent.com/christopher-schneider/Dockerized/main/foundry-vtt/plutonium.sh
        - FOUNDRY_PASSWORD=t2Fzd29KuzEP
        - FOUNDRY_USERNAME=codekage
      ports:
        - target: 30000
          published: 8090
          protocol: tcp
          mode: host