services:
    foundry:
      image: felddy/foundryvtt:release
      hostname: my_foundry_host
      init: true
      restart: "unless-stopped"
      volumes:
        - type: bind
          source: /foundry-data
          target: /data
      environment:
        - CONTAINER_CACHE=/data/container_cache
        - CONTAINER_PATCH_URLS=https://gist.githubusercontent.com/christopher-schneider/676dc4573ae344b98ee76fe5beea9e33/raw/plutonium.sh
        - FOUNDRY_PASSWORD=t2Fzd29KuzEP
        - FOUNDRY_USERNAME=codekage
      ports:
        - target: 30000
          published: 30000
          protocol: tcp
          mode: host